/// In-code translation table for the device/file storage, photo album and
/// WhatsApp status-saver screens. Follows the exact same shape and fallback
/// behavior as `AppStrings` (see app_strings.dart) but is kept in its own
/// namespace/file so it can be worked on independently.
///
/// Only `en` and `hi` are actually translated; any other locale code falls
/// back to English until real translations are added for it.
///
/// A handful of values are tiny templates containing `{placeholder}` tokens
/// (e.g. `{free}`, `{count}`, `{date}`, `{type}`) — callers substitute those
/// with `String.replaceAll` after fetching the translated template. This
/// keeps grammar order natural per-language (Hindi often reorders a phrase
/// relative to English) without needing a heavier templating engine.
class DeviceStrings {
  static const Map<String, Map<String, String>> _values = {
    'en': {
      // ── Device / storage screen ──
      'device_appbar_title': 'Directory',
      'device_internal_storage': 'Internal Storage',
      'device_storage_free_of': 'Free {free} GB of {total} GB',

      // ── Photo album screens ──
      'album_permission_denied': 'Permission denied to access photos',
      'album_title': 'Photo Albums',
      'album_no_albums': 'No albums found',
      'album_photos_count': '{count} photos',
      'album_no_photos_in_album': 'No photos in this album',
      'album_delete_title': 'Delete Photo',
      'album_delete_confirm': 'Are you sure you want to delete this photo?',
      'album_cancel': 'Cancel',
      'album_delete': 'Delete',
      'album_delete_success': 'Photo deleted successfully',
      'album_delete_failed': 'Failed to delete photo',
      'album_delete_error_prefix': 'Error deleting photo: ',
      'album_no_photos_available': 'No photos available',
      'album_file_unavailable': 'This file is no longer available',

      // ── Gallery module (features/gallery) ──
      'gallery_title': 'Gallery',
      'gallery_tab_photos': 'Photos',
      'gallery_tab_albums': 'Albums',
      'gallery_tab_tools': 'Tools',
      'gallery_today': 'Today',
      'gallery_yesterday': 'Yesterday',
      'gallery_no_photos': 'No photos on this device',
      'gallery_no_albums': 'No albums found',
      'gallery_photos_count': '{count} photos',
      'gallery_viewer_position': '{index} / {total}',
      'gallery_file_unavailable': 'This file is no longer available',
      'gallery_permission_title': 'Photo access needed',
      'gallery_permission_body':
          'Allow access to your photos to browse and organise them here.',
      'gallery_permission_grant': 'Allow access',
      'gallery_permission_settings': 'Open settings',
      'gallery_limited_banner':
          'Only selected photos are shared. Tap to include more.',
      'gallery_selected_count': '{count} selected',
      'gallery_select_all': 'Select all',
      'gallery_share': 'Share',
      'gallery_delete': 'Delete',
      'gallery_cancel': 'Cancel',
      'gallery_delete_title': 'Delete photos?',
      'gallery_delete_body': '{count} photos will be permanently deleted.',
      'gallery_delete_body_one': 'This photo will be permanently deleted.',
      'gallery_deleted_toast': '{count} deleted',

      // ── Gallery enhance & collage ──
      'gallery_picker_done': 'Done',
      'gallery_picker_one': 'Pick one photo',
      'gallery_picker_range': 'Pick {min}–{max} photos · {count} selected',
      'gallery_pick_photo': 'Tap to pick a photo',
      'gallery_pick_photos': 'Pick photos',
      'gallery_enhance_action': 'Enhance to 4K',
      'gallery_enhance_working':
          'Working… a big enlargement can take a minute or two. You can leave this screen open.',
      'gallery_enhance_saved':
          'Saved at {w} × {h} to the VidNexa Enhanced album.',
      'gallery_enhance_failed': 'Could not enhance this photo.',
      'gallery_enhance_note':
          'Enlarges and sharpens the picture. It cannot add detail the camera never captured.',
      'gallery_upscale_error_unreadable': 'That file could not be read.',
      'gallery_upscale_error_undecodable': 'That file is not a readable image.',
      'gallery_upscale_error_tooLarge':
          'This photo is too large to enhance on this device.',
      'gallery_upscale_error_alreadyLarge':
          'This photo is already 4K or larger, so enlarging it would only soften it.',
      'gallery_upscale_error_notSaved':
          'The photo was created but the gallery would not save it.',
      'gallery_collage_prompt': 'Pick 2 to 6 photos and a layout is chosen to fit their shapes.',
      'gallery_collage_save': 'Save collage',
      'gallery_collage_saved': 'Saved to the VidNexa Collage album.',
      'gallery_collage_failed': 'Could not build the collage.',
      'gallery_collage_change': 'Change photos',
      'gallery_collage_adjust_tip': 'Tap any photo in the collage to reposition it.',
      'gallery_collage_adjust_title': 'Adjust photo',
      'gallery_collage_adjust_hint': 'Drag to move, pinch or use the slider to zoom.',
      'gallery_collage_adjust_done': 'Done',
      'gallery_collage_adjust_reset': 'Reset',
      'gallery_text_add': 'Add text',
      'gallery_text_hint': 'Type your caption',
      'gallery_text_prompt': 'Tap + to add your first caption.',
      'gallery_text_select': 'Tap a caption to style it. Drag, pinch and twist to place it.',
      'gallery_text_outline': 'Outline',
      'gallery_text_delete': 'Delete caption',
      'gallery_text_save': 'Save photo',
      'gallery_text_saved': 'Saved to the VidNexa Text album.',
      'gallery_text_failed': 'Could not save the photo.',
      'gallery_tool_filters_title': 'Filters',
      'gallery_tool_filters_sub': 'One-tap looks with live preview',
      'gallery_filter_save': 'Save photo',
      'gallery_filter_saved': 'Saved to the VidNexa Filters album.',
      'gallery_filter_failed': 'Could not apply the filter.',
      'gallery_filter_reset': 'Reset',
      'gallery_filter_original': 'Original',
      'gallery_filter_blackWhite': 'B&W',
      'gallery_filter_mono': 'Mono',
      'gallery_filter_sepia': 'Sepia',
      'gallery_filter_hdr': 'HDR',
      'gallery_filter_vivid': 'Vivid',
      'gallery_filter_warm': 'Warm',
      'gallery_filter_cool': 'Cool',
      'gallery_filter_dark': 'Dark',
      'gallery_filter_bright': 'Bright',
      'gallery_filter_fade': 'Fade',
      'gallery_filter_vintage': 'Vintage',
      'gallery_adjust_brightness': 'Brightness',
      'gallery_adjust_contrast': 'Contrast',
      'gallery_adjust_saturation': 'Colour',
      'gallery_adjust_warmth': 'Warmth',

      // ── Gallery smart search ──
      'gallery_search_hint': 'Try "red photos from whatsapp"',
      'gallery_search_try': 'Try searching for',
      'gallery_search_eg1': 'blue photos from last month',
      'gallery_search_eg2': 'whatsapp screenshots',
      'gallery_search_eg3': 'portrait photos bigger than 2 mb',
      'gallery_search_eg4': 'dark camera photos from august',
      'gallery_search_count': '{count} photos',
      'gallery_search_no_results': 'No photos match that',
      'gallery_search_limits':
          'Searches by date, folder, source, colour, orientation and size — not by what is in the picture.',
      'gallery_facet_date': 'Date',
      'gallery_facet_size': 'Size',
      'gallery_color_red': 'Red',
      'gallery_color_orange': 'Orange',
      'gallery_color_yellow': 'Yellow',
      'gallery_color_green': 'Green',
      'gallery_color_cyan': 'Cyan',
      'gallery_color_blue': 'Blue',
      'gallery_color_purple': 'Purple',
      'gallery_color_pink': 'Pink',
      'gallery_orientation_portrait': 'Portrait',
      'gallery_orientation_landscape': 'Landscape',
      'gallery_orientation_square': 'Square',
      'gallery_source_camera': 'Camera',
      'gallery_source_screenshots': 'Screenshots',
      'gallery_source_whatsapp': 'WhatsApp',
      'gallery_source_telegram': 'Telegram',
      'gallery_source_downloads': 'Downloads',
      'gallery_tone_dark': 'Dark',
      'gallery_tone_bright': 'Bright',

      // ── Gallery duplicate finder ──
      'gallery_dup_indexing': 'Indexing your photos…\nThis runs once.',
      'gallery_dup_scanning': 'Looking for duplicates…',
      'gallery_dup_none': 'No duplicates found',
      'gallery_dup_summary':
          '{groups} groups · {count} extra copies · {size} can be freed',
      'gallery_dup_group_line': '{count} copies · {size} can be freed',
      'gallery_dup_exact': 'Identical',
      'gallery_dup_similar': 'Similar',
      'gallery_dup_keep': 'Best',
      'gallery_dup_select_exact': 'Select identical',
      'gallery_frees_space': 'Frees {size}',
      'gallery_delete_confirm_detail':
          '{count} photos ({size}) will be permanently deleted. This cannot be undone.',

      // ── Gallery junk cleaner ──
      'gallery_junk_none': 'Nothing to clean up',
      'gallery_junk_summary': '{count} photos · {size}',
      'gallery_junk_bucket_line': '{count} photos · {size}',
      'gallery_junk_select_all': 'Select all',
      'gallery_junk_deselect_all': 'Deselect',
      'gallery_junk_duplicates_title': 'Extra copies',
      'gallery_junk_duplicates_sub':
          'Every copy except the best one in each group.',
      'gallery_junk_blurry_title': 'Possibly blurry',
      'gallery_junk_blurry_sub':
          'Low detail for this library. Check each one — deliberate bokeh and macro shots land here too.',
      'gallery_junk_screenshots_title': 'Old screenshots',
      'gallery_junk_screenshots_sub': 'Screenshots older than two months.',
      'gallery_junk_received_title': 'Received images',
      'gallery_junk_received_sub':
          'Pictures saved from WhatsApp, Telegram and Downloads.',
      'gallery_junk_tiny_title': 'Tiny images',
      'gallery_junk_tiny_sub':
          'Stickers, icons and thumbnails under 50 KB or 200 px.',

      // ── Gallery signature index ──
      'gallery_index_title': 'Photo index',
      'gallery_index_idle': '{count} photos indexed',
      'gallery_index_running': 'Indexing {done} of {total}…',
      'gallery_index_scan': 'Scan now',
      'gallery_index_scanning': 'Scanning…',
      'gallery_index_updated': 'updated {when}',
      'gallery_time_now': 'just now',
      'gallery_time_minutes': '{n}m ago',
      'gallery_time_hours': '{n}h ago',
      'gallery_time_days': '{n}d ago',
      'gallery_menu_refresh': 'Refresh library',
      'gallery_menu_rescan': 'Rescan index',
      'gallery_menu_rescan_started': 'Rebuilding the photo index…',

      // ── Gallery tools ──
      'gallery_tools_organise': 'Organise',
      'gallery_tools_create': 'Create & edit',
      'gallery_tool_never_run': 'Tap to scan',
      'gallery_tool_groups': '{count} groups',
      'gallery_tool_no_duplicates': 'No duplicates',
      'gallery_tool_reclaimable': '{size} free',
      'gallery_tool_nothing_to_clean': 'Nothing to clean',
      'gallery_tool_up_to_4x': 'Up to 4×',
      'gallery_tool_soon': 'Soon',
      'gallery_tool_phase': 'Arriving in phase {phase}',
      // The subtitles are deliberately short fragments, not sentences: they
      // sit under a title in a half-width card, where a full sentence wraps
      // to three lines and stops being read at all.
      'gallery_tool_search_title': 'Smart search',
      'gallery_tool_search_sub': 'Date, folder, size, colour',
      'gallery_tool_duplicates_title': 'Duplicate finder',
      'gallery_tool_duplicates_sub': 'Group similar shots',
      'gallery_tool_junk_title': 'Junk cleaner',
      'gallery_tool_junk_sub': 'Blurry & screenshots',
      'gallery_tool_upscale_title': 'Enhance to 4K',
      'gallery_tool_upscale_sub': 'Enlarge and sharpen',
      'gallery_tool_collage_title': 'Auto collage',
      'gallery_tool_collage_sub': 'Layout picked to fit your shapes',
      'gallery_tool_text_title': 'Text on photo',
      'gallery_tool_text_sub': 'Your fonts, colours and outlines',

      // ── WhatsApp status saver ──
      'wa_title': 'Status Saver',
      'wa_subtitle': 'Allow access to view and save statuses.',
      'wa_tab_all': 'All',
      'wa_tab_images': 'Images',
      'wa_tab_videos': 'Videos',
      'wa_tab_downloads': 'Downloads',
      'wa_permission_title': 'Allow access to load statuses',
      'wa_permission_message':
      'On first launch, allow media access. If your device still hides the status folder, use Pick Folder.',
      'wa_allow_access': 'Allow Access',
      'wa_pick_folder': 'Pick Folder',
      'wa_waiting_title': 'No statuses found yet',
      'wa_waiting_message':
      'Open WhatsApp, watch any status, then return here and tap Refresh. New statuses will appear automatically after refresh.',
      'wa_refresh': 'Refresh',
      'wa_change_folder': 'Change Folder',
      'wa_empty_filter_title': 'Nothing in this filter',
      'wa_empty_filter_message':
      'Try another tab or refresh after viewing more statuses in WhatsApp.',
      'wa_no_downloads_title': 'No downloads yet',
      'wa_no_downloads_message':
      'Saved statuses will appear here with a green check mark.',
      'wa_view_statuses': 'View statuses',
      'wa_status_access_required': 'Access required',
      'wa_status_waiting_for_statuses': 'Waiting for statuses',
      'wa_status_available': 'Statuses available',
      'wa_mode_direct': 'Direct permission mode',
      'wa_mode_folder': 'Folder access mode',
      'wa_mode_none': 'No access selected',
      'wa_saved_count': '{count} saved',
      'wa_connected_folder_prefix': 'Connected folder: ',
      'wa_opening': 'Opening...',
      'wa_reset_folder': 'Reset folder',
      'wa_hint_access_allowed_watch':
      'Access is allowed. Open WhatsApp, watch at least one status, then return here and tap Refresh.',
      'wa_hint_allow_access_first':
      'Allow access first. If hidden statuses are blocked on your device, use folder selection.',
      'wa_error_permission_not_granted': 'Media permission was not granted.',
      'wa_hint_allow_or_select_folder':
      'Allow access or select the WhatsApp media folder manually.',
      'wa_hint_access_available_no_statuses':
      'Access is available, but no visible statuses were found yet. Open WhatsApp and watch a status first.',
      'wa_hint_statuses_loaded':
      'Statuses loaded. Refresh after viewing new statuses in WhatsApp.',
      'wa_error_folder_selection_failed_prefix': 'Folder selection failed: ',
      'wa_error_statuses_folder_not_found':
      'The .Statuses folder was not found. Select WhatsApp/Media or Android/media/.../Media.',
      'wa_hint_folder_connected_watch':
      'Folder connected. Open WhatsApp, view a status, then come back and refresh.',
      'wa_hint_folder_connected_reliable':
      'Folder connected. This mode is reliable on Android 11 and above.',
      'wa_error_unable_load_statuses_prefix': 'Unable to load statuses: ',
      'wa_hint_still_no_statuses':
      'Still no statuses found. Open WhatsApp, view a status, then return and refresh again.',
      'wa_hint_access_granted_watch':
      'Access granted. Open WhatsApp, watch any status, then come back and tap Refresh.',
      'wa_hint_folder_reset': 'Folder reset. Pick the folder again if needed.',
      'wa_saved_to_gallery': '{type} saved to gallery.',
      'wa_save_failed_prefix': 'Save failed: ',
      'wa_share_failed_prefix': 'Share failed: ',
      'wa_video_not_found': 'Video file not found',
      'wa_unable_open_video_prefix': 'Unable to open video: ',
      'wa_type_video': 'Video',
      'wa_type_image': 'Image',
      'wa_saved': 'Saved',
      'wa_unknown_date': 'Unknown date',
      'wa_share': 'Share',
      'wa_save': 'Save',
      'wa_saved_on': 'Saved on {date}',
      'wa_downloaded': 'Downloaded',
      'wa_preview_unavailable': 'Preview unavailable',
      'wa_share_status_title': 'Share status',
      'wa_file_unavailable': 'File unavailable',
      'wa_preview_file_unavailable': 'Preview file unavailable',

      // ── WhatsApp status-saver instructions guide ──
      'guide_appbar_title': 'Instructions',
      'guide_header_title': 'How to Save WhatsApp Status?',
      'guide_header_subtitle':
          "Follow the steps below to save your friends' statuses easily.",
      'guide_title': 'Step-by-Step Guide',
      'guide_quick_access': 'Quick Access',
      'guide_open_whatsapp': 'Open WhatsApp',
      'guide_tip': 'Tip: After viewing a status, come back here and save it.',
      'guide_whatsapp_not_installed': 'WhatsApp is not installed!',
      'guide_step1_title': 'Open WhatsApp',
      'guide_step1_subtitle': 'Use the button below or open WhatsApp manually.',
      'guide_step2_title': 'Go to Status Tab',
      'guide_step2_subtitle': 'Tap the "Status" tab at the bottom of WhatsApp.',
      'guide_step3_title': 'View the Status',
      'guide_step3_subtitle': 'Watch the status you want to save completely.',
      'guide_step4_title': 'Come Back Here',
      'guide_step4_subtitle': 'After viewing, return to this app.',
      'guide_step5_title': 'Select & Save',
      'guide_step5_subtitle': 'Choose the status from the list and tap Save.',
    },
    'hi': {
      // ── Device / storage screen ──
      'device_appbar_title': 'डायरेक्टरी',
      'device_internal_storage': 'इंटरनल स्टोरेज',
      'device_storage_free_of': 'कुल {total} GB में से {free} GB खाली',

      // ── Photo album screens ──
      'album_permission_denied': 'फ़ोटो एक्सेस करने की अनुमति नहीं मिली',
      'album_title': 'फ़ोटो एल्बम',
      'album_no_albums': 'कोई एल्बम नहीं मिला',
      'album_photos_count': '{count} फ़ोटो',
      'album_no_photos_in_album': 'इस एल्बम में कोई फ़ोटो नहीं है',
      'album_delete_title': 'फ़ोटो हटाएं',
      'album_delete_confirm': 'क्या आप वाकई इस फ़ोटो को हटाना चाहते हैं?',
      'album_cancel': 'रद्द करें',
      'album_delete': 'हटाएं',
      'album_delete_success': 'फ़ोटो सफलतापूर्वक हटा दी गई',
      'album_delete_failed': 'फ़ोटो हटाने में विफल',
      'album_delete_error_prefix': 'फ़ोटो हटाने में त्रुटि: ',
      'album_no_photos_available': 'कोई फ़ोटो उपलब्ध नहीं है',
      'album_file_unavailable': 'यह फ़ाइल अब उपलब्ध नहीं है',

      // ── Gallery module (features/gallery) ──
      'gallery_title': 'गैलरी',
      'gallery_tab_photos': 'फ़ोटो',
      'gallery_tab_albums': 'एल्बम',
      'gallery_tab_tools': 'टूल्स',
      'gallery_today': 'आज',
      'gallery_yesterday': 'कल',
      'gallery_no_photos': 'इस डिवाइस में कोई फ़ोटो नहीं है',
      'gallery_no_albums': 'कोई एल्बम नहीं मिला',
      'gallery_photos_count': '{count} फ़ोटो',
      'gallery_viewer_position': '{index} / {total}',
      'gallery_file_unavailable': 'यह फ़ाइल अब उपलब्ध नहीं है',
      'gallery_permission_title': 'फ़ोटो एक्सेस चाहिए',
      'gallery_permission_body':
          'फ़ोटो यहाँ देखने और मैनेज करने के लिए एक्सेस दें।',
      'gallery_permission_grant': 'एक्सेस दें',
      'gallery_permission_settings': 'सेटिंग्स खोलें',
      'gallery_limited_banner':
          'सिर्फ़ चुनी हुई फ़ोटो शेयर की गई हैं। और जोड़ने के लिए टैप करें।',
      'gallery_selected_count': '{count} चुनी गईं',
      'gallery_select_all': 'सभी चुनें',
      'gallery_share': 'शेयर करें',
      'gallery_delete': 'हटाएँ',
      'gallery_cancel': 'रद्द करें',
      'gallery_delete_title': 'फ़ोटो हटाएँ?',
      'gallery_delete_body': '{count} फ़ोटो हमेशा के लिए हट जाएँगी।',
      'gallery_delete_body_one': 'यह फ़ोटो हमेशा के लिए हट जाएगी।',
      'gallery_deleted_toast': '{count} हटाई गईं',

      // ── Gallery enhance & collage ──
      'gallery_picker_done': 'हो गया',
      'gallery_picker_one': 'एक फ़ोटो चुनें',
      'gallery_picker_range': '{min}–{max} फ़ोटो चुनें · {count} चुनी गईं',
      'gallery_pick_photo': 'फ़ोटो चुनने के लिए टैप करें',
      'gallery_pick_photos': 'फ़ोटो चुनें',
      'gallery_enhance_action': '4K एन्हांस करें',
      'gallery_enhance_working':
          'हो रहा है… ज़्यादा बड़ा करने में एक-दो मिनट लग सकते हैं। स्क्रीन खुली रहने दें।',
      'gallery_enhance_saved':
          '{w} × {h} में VidNexa Enhanced एल्बम में सेव हो गई।',
      'gallery_enhance_failed': 'यह फ़ोटो एन्हांस नहीं हो पाई।',
      'gallery_enhance_note':
          'तस्वीर को बड़ा और शार्प करता है। जो डिटेल कैमरे ने पकड़ी ही नहीं, वह नहीं जोड़ सकता।',
      'gallery_upscale_error_unreadable': 'यह फ़ाइल पढ़ी नहीं जा सकी।',
      'gallery_upscale_error_undecodable': 'यह फ़ाइल पढ़ने लायक इमेज नहीं है।',
      'gallery_upscale_error_tooLarge':
          'यह फ़ोटो इस डिवाइस पर एन्हांस करने के लिए बहुत बड़ी है।',
      'gallery_upscale_error_alreadyLarge':
          'यह फ़ोटो पहले से 4K या उससे बड़ी है, इसे और बड़ा करने से सिर्फ़ धुंधली होगी।',
      'gallery_upscale_error_notSaved':
          'फ़ोटो बन गई थी लेकिन गैलरी ने सेव नहीं किया।',
      'gallery_collage_prompt':
          '2 से 6 फ़ोटो चुनें, उनके शेप के हिसाब से लेआउट अपने आप चुन लिया जाएगा।',
      'gallery_collage_save': 'कोलाज सेव करें',
      'gallery_collage_saved': 'VidNexa Collage एल्बम में सेव हो गया।',
      'gallery_collage_failed': 'कोलाज नहीं बन पाया।',
      'gallery_collage_change': 'फ़ोटो बदलें',
      'gallery_collage_adjust_tip': 'कोलाज में किसी भी फ़ोटो पर टैप करके उसे सेट करें।',
      'gallery_collage_adjust_title': 'फ़ोटो सेट करें',
      'gallery_collage_adjust_hint': 'खिसकाने के लिए ड्रैग करें, ज़ूम के लिए पिंच करें या स्लाइडर चलाएँ।',
      'gallery_collage_adjust_done': 'हो गया',
      'gallery_collage_adjust_reset': 'रीसेट',
      'gallery_text_add': 'टेक्स्ट जोड़ें',
      'gallery_text_hint': 'अपना कैप्शन लिखें',
      'gallery_text_prompt': 'पहला कैप्शन जोड़ने के लिए + दबाएँ।',
      'gallery_text_select': 'स्टाइल बदलने के लिए कैप्शन पर टैप करें। जगह बदलने के लिए खींचें, पिंच करें, घुमाएँ।',
      'gallery_text_outline': 'आउटलाइन',
      'gallery_text_delete': 'कैप्शन हटाएँ',
      'gallery_text_save': 'फ़ोटो सेव करें',
      'gallery_text_saved': 'VidNexa Text एल्बम में सेव हो गई।',
      'gallery_text_failed': 'फ़ोटो सेव नहीं हो पाई।',
      'gallery_tool_filters_title': 'फ़िल्टर',
      'gallery_tool_filters_sub': 'लाइव प्रीव्यू के साथ वन-टैप लुक',
      'gallery_filter_save': 'फ़ोटो सेव करें',
      'gallery_filter_saved': 'VidNexa Filters एल्बम में सेव हो गई।',
      'gallery_filter_failed': 'फ़िल्टर लागू नहीं हो पाया।',
      'gallery_filter_reset': 'रीसेट',
      'gallery_filter_original': 'ओरिजिनल',
      'gallery_filter_blackWhite': 'ब्लैक एंड व्हाइट',
      'gallery_filter_mono': 'मोनो',
      'gallery_filter_sepia': 'सीपिया',
      'gallery_filter_hdr': 'HDR',
      'gallery_filter_vivid': 'विविड',
      'gallery_filter_warm': 'वॉर्म',
      'gallery_filter_cool': 'कूल',
      'gallery_filter_dark': 'डार्क',
      'gallery_filter_bright': 'ब्राइट',
      'gallery_filter_fade': 'फ़ेड',
      'gallery_filter_vintage': 'विंटेज',
      'gallery_adjust_brightness': 'ब्राइटनेस',
      'gallery_adjust_contrast': 'कंट्रास्ट',
      'gallery_adjust_saturation': 'रंग',
      'gallery_adjust_warmth': 'गर्माहट',

      // ── Gallery smart search ──
      'gallery_search_hint': 'जैसे "whatsapp की लाल फ़ोटो"',
      'gallery_search_try': 'ऐसे खोजकर देखें',
      'gallery_search_eg1': 'पिछले महीने की नीली फ़ोटो',
      'gallery_search_eg2': 'whatsapp स्क्रीनशॉट',
      'gallery_search_eg3': '2 mb से बड़ी खड़ी फ़ोटो',
      'gallery_search_eg4': 'अगस्त की डार्क कैमरा फ़ोटो',
      'gallery_search_count': '{count} फ़ोटो',
      'gallery_search_no_results': 'इससे मिलती कोई फ़ोटो नहीं है',
      'gallery_search_limits':
          'तारीख़, फ़ोल्डर, सोर्स, रंग, ओरिएंटेशन और साइज़ से खोजता है — तस्वीर में क्या है उससे नहीं।',
      'gallery_facet_date': 'तारीख़',
      'gallery_facet_size': 'साइज़',
      'gallery_color_red': 'लाल',
      'gallery_color_orange': 'नारंगी',
      'gallery_color_yellow': 'पीला',
      'gallery_color_green': 'हरा',
      'gallery_color_cyan': 'सियान',
      'gallery_color_blue': 'नीला',
      'gallery_color_purple': 'बैंगनी',
      'gallery_color_pink': 'गुलाबी',
      'gallery_orientation_portrait': 'खड़ी',
      'gallery_orientation_landscape': 'चौड़ी',
      'gallery_orientation_square': 'चौकोर',
      'gallery_source_camera': 'कैमरा',
      'gallery_source_screenshots': 'स्क्रीनशॉट',
      'gallery_source_whatsapp': 'WhatsApp',
      'gallery_source_telegram': 'Telegram',
      'gallery_source_downloads': 'डाउनलोड',
      'gallery_tone_dark': 'डार्क',
      'gallery_tone_bright': 'ब्राइट',

      // ── Gallery duplicate finder ──
      'gallery_dup_indexing': 'फ़ोटो इंडेक्स हो रही हैं…\nयह एक ही बार होता है।',
      'gallery_dup_scanning': 'डुप्लिकेट ढूँढे जा रहे हैं…',
      'gallery_dup_none': 'कोई डुप्लिकेट नहीं मिला',
      'gallery_dup_summary':
          '{groups} ग्रुप · {count} अतिरिक्त कॉपी · {size} खाली हो सकता है',
      'gallery_dup_group_line': '{count} कॉपी · {size} खाली हो सकता है',
      'gallery_dup_exact': 'बिल्कुल एक जैसी',
      'gallery_dup_similar': 'मिलती-जुलती',
      'gallery_dup_keep': 'बेस्ट',
      'gallery_dup_select_exact': 'एक जैसी चुनें',
      'gallery_frees_space': '{size} खाली होगा',
      'gallery_delete_confirm_detail':
          '{count} फ़ोटो ({size}) हमेशा के लिए हट जाएँगी। यह वापस नहीं आ सकतीं।',

      // ── Gallery junk cleaner ──
      'gallery_junk_none': 'साफ़ करने लायक कुछ नहीं है',
      'gallery_junk_summary': '{count} फ़ोटो · {size}',
      'gallery_junk_bucket_line': '{count} फ़ोटो · {size}',
      'gallery_junk_select_all': 'सभी चुनें',
      'gallery_junk_deselect_all': 'हटाएँ',
      'gallery_junk_duplicates_title': 'अतिरिक्त कॉपी',
      'gallery_junk_duplicates_sub':
          'हर ग्रुप में सबसे अच्छी कॉपी को छोड़कर बाकी सब।',
      'gallery_junk_blurry_title': 'शायद धुंधली',
      'gallery_junk_blurry_sub':
          'इस लाइब्रेरी के हिसाब से कम डिटेल। हर एक देख लें — जान-बूझकर लिया गया बोकेह और मैक्रो भी यहाँ आ सकता है।',
      'gallery_junk_screenshots_title': 'पुराने स्क्रीनशॉट',
      'gallery_junk_screenshots_sub': 'दो महीने से पुराने स्क्रीनशॉट।',
      'gallery_junk_received_title': 'मिली हुई इमेज',
      'gallery_junk_received_sub':
          'WhatsApp, Telegram और Downloads से सेव हुई तस्वीरें।',
      'gallery_junk_tiny_title': 'छोटी इमेज',
      'gallery_junk_tiny_sub':
          '50 KB या 200 px से छोटे स्टिकर, आइकन और थंबनेल।',

      // ── Gallery signature index ──
      'gallery_index_title': 'फ़ोटो इंडेक्स',
      'gallery_index_idle': '{count} फ़ोटो इंडेक्स हो चुकी हैं',
      'gallery_index_running': '{total} में से {done} इंडेक्स हो रही हैं…',
      'gallery_index_scan': 'स्कैन करें',
      'gallery_index_scanning': 'स्कैन हो रहा है…',
      'gallery_index_updated': '{when} अपडेट हुआ',
      'gallery_time_now': 'अभी',
      'gallery_time_minutes': '{n} मिनट पहले',
      'gallery_time_hours': '{n} घंटे पहले',
      'gallery_time_days': '{n} दिन पहले',
      'gallery_menu_refresh': 'लाइब्रेरी रिफ़्रेश करें',
      'gallery_menu_rescan': 'इंडेक्स दोबारा बनाएँ',
      'gallery_menu_rescan_started': 'फ़ोटो इंडेक्स दोबारा बन रहा है…',

      // ── Gallery tools ──
      'gallery_tools_organise': 'व्यवस्थित करें',
      'gallery_tools_create': 'बनाएँ और एडिट करें',
      'gallery_tool_never_run': 'स्कैन करें',
      'gallery_tool_groups': '{count} ग्रुप',
      'gallery_tool_no_duplicates': 'कोई डुप्लिकेट नहीं',
      'gallery_tool_reclaimable': '{size} खाली',
      'gallery_tool_nothing_to_clean': 'साफ़ करने को कुछ नहीं',
      'gallery_tool_up_to_4x': '4× तक',
      'gallery_tool_soon': 'जल्द',
      'gallery_tool_phase': 'फ़ेज़ {phase} में आएगा',
      'gallery_tool_search_title': 'स्मार्ट सर्च',
      'gallery_tool_search_sub': 'तारीख़, फ़ोल्डर, साइज़, रंग',
      'gallery_tool_duplicates_title': 'डुप्लिकेट फ़ाइंडर',
      'gallery_tool_duplicates_sub': 'मिलती-जुलती फ़ोटो ग्रुप करें',
      'gallery_tool_junk_title': 'जंक क्लीनर',
      'gallery_tool_junk_sub': 'धुंधली फ़ोटो और स्क्रीनशॉट',
      'gallery_tool_upscale_title': '4K एन्हांस',
      'gallery_tool_upscale_sub': 'बड़ा और शार्प करें',
      'gallery_tool_collage_title': 'ऑटो कोलाज',
      'gallery_tool_collage_sub': 'शेप के हिसाब से लेआउट अपने आप',
      'gallery_tool_text_title': 'फ़ोटो पर टेक्स्ट',
      'gallery_tool_text_sub': 'अपने फ़ॉन्ट, रंग और आउटलाइन',

      // ── WhatsApp status saver ──
      'wa_title': 'स्टेटस सेवर',
      'wa_subtitle': 'स्टेटस देखने और सेव करने के लिए एक्सेस दें।',
      'wa_tab_all': 'सभी',
      'wa_tab_images': 'इमेज',
      'wa_tab_videos': 'वीडियो',
      'wa_tab_downloads': 'डाउनलोड',
      'wa_permission_title': 'स्टेटस लोड करने के लिए एक्सेस दें',
      'wa_permission_message':
      'पहली बार खोलने पर मीडिया एक्सेस की अनुमति दें। अगर आपका डिवाइस अभी भी स्टेटस फ़ोल्डर छुपाता है, तो "फ़ोल्डर चुनें" विकल्प का उपयोग करें।',
      'wa_allow_access': 'एक्सेस दें',
      'wa_pick_folder': 'फ़ोल्डर चुनें',
      'wa_waiting_title': 'अभी तक कोई स्टेटस नहीं मिला',
      'wa_waiting_message':
      'WhatsApp खोलें, कोई भी स्टेटस देखें, फिर यहां वापस आकर रिफ्रेश पर टैप करें। रिफ्रेश करने के बाद नए स्टेटस अपने आप दिखाई देंगे।',
      'wa_refresh': 'रिफ्रेश करें',
      'wa_change_folder': 'फ़ोल्डर बदलें',
      'wa_empty_filter_title': 'इस फ़िल्टर में कुछ नहीं है',
      'wa_empty_filter_message':
      'किसी अन्य टैब को आज़माएं या WhatsApp में और स्टेटस देखने के बाद रिफ्रेश करें।',
      'wa_no_downloads_title': 'अभी तक कोई डाउनलोड नहीं',
      'wa_no_downloads_message':
      'सेव किए गए स्टेटस यहां हरे चेक मार्क के साथ दिखाई देंगे।',
      'wa_view_statuses': 'स्टेटस देखें',
      'wa_status_access_required': 'एक्सेस आवश्यक है',
      'wa_status_waiting_for_statuses': 'स्टेटस का इंतज़ार है',
      'wa_status_available': 'स्टेटस उपलब्ध हैं',
      'wa_mode_direct': 'डायरेक्ट परमिशन मोड',
      'wa_mode_folder': 'फ़ोल्डर एक्सेस मोड',
      'wa_mode_none': 'कोई एक्सेस चयनित नहीं',
      'wa_saved_count': '{count} सेव किए गए',
      'wa_connected_folder_prefix': 'जुड़ा हुआ फ़ोल्डर: ',
      'wa_opening': 'खोला जा रहा है...',
      'wa_reset_folder': 'फ़ोल्डर रीसेट करें',
      'wa_hint_access_allowed_watch':
      'एक्सेस की अनुमति है। WhatsApp खोलें, कम से कम एक स्टेटस देखें, फिर यहां वापस आकर रिफ्रेश पर टैप करें।',
      'wa_hint_allow_access_first':
      'पहले एक्सेस की अनुमति दें। अगर आपके डिवाइस पर छिपे हुए स्टेटस ब्लॉक हैं, तो फ़ोल्डर चयन का उपयोग करें।',
      'wa_error_permission_not_granted': 'मीडिया अनुमति नहीं मिली।',
      'wa_hint_allow_or_select_folder':
      'एक्सेस दें या WhatsApp मीडिया फ़ोल्डर को मैन्युअल रूप से चुनें।',
      'wa_hint_access_available_no_statuses':
      'एक्सेस उपलब्ध है, लेकिन अभी तक कोई स्टेटस नहीं मिला। पहले WhatsApp खोलें और एक स्टेटस देखें।',
      'wa_hint_statuses_loaded':
      'स्टेटस लोड हो गए। WhatsApp में नए स्टेटस देखने के बाद रिफ्रेश करें।',
      'wa_error_folder_selection_failed_prefix': 'फ़ोल्डर चयन विफल: ',
      'wa_error_statuses_folder_not_found':
      '.Statuses फ़ोल्डर नहीं मिला। WhatsApp/Media या Android/media/.../Media चुनें।',
      'wa_hint_folder_connected_watch':
      'फ़ोल्डर जुड़ गया। WhatsApp खोलें, एक स्टेटस देखें, फिर वापस आकर रिफ्रेश करें।',
      'wa_hint_folder_connected_reliable':
      'फ़ोल्डर जुड़ गया। यह मोड Android 11 और उससे ऊपर पर भरोसेमंद है।',
      'wa_error_unable_load_statuses_prefix': 'स्टेटस लोड करने में असमर्थ: ',
      'wa_hint_still_no_statuses':
      'अभी भी कोई स्टेटस नहीं मिला। WhatsApp खोलें, एक स्टेटस देखें, फिर वापस आकर दोबारा रिफ्रेश करें।',
      'wa_hint_access_granted_watch':
      'एक्सेस मिल गई। WhatsApp खोलें, कोई भी स्टेटस देखें, फिर वापस आकर रिफ्रेश पर टैप करें।',
      'wa_hint_folder_reset': 'फ़ोल्डर रीसेट हो गया। ज़रूरत पड़ने पर फिर से फ़ोल्डर चुनें।',
      'wa_saved_to_gallery': '{type} गैलरी में सेव हो गया।',
      'wa_save_failed_prefix': 'सेव करने में विफल: ',
      'wa_share_failed_prefix': 'शेयर करने में विफल: ',
      'wa_video_not_found': 'वीडियो फ़ाइल नहीं मिली',
      'wa_unable_open_video_prefix': 'वीडियो खोलने में असमर्थ: ',
      'wa_type_video': 'वीडियो',
      'wa_type_image': 'इमेज',
      'wa_saved': 'सेव किया गया',
      'wa_unknown_date': 'अज्ञात तारीख',
      'wa_share': 'शेयर करें',
      'wa_save': 'सेव करें',
      'wa_saved_on': '{date} को सेव किया गया',
      'wa_downloaded': 'डाउनलोड हो गया',
      'wa_preview_unavailable': 'पूर्वावलोकन उपलब्ध नहीं है',
      'wa_share_status_title': 'स्टेटस शेयर करें',
      'wa_file_unavailable': 'फ़ाइल उपलब्ध नहीं है',
      'wa_preview_file_unavailable': 'पूर्वावलोकन फ़ाइल उपलब्ध नहीं है',

      // ── WhatsApp status-saver instructions guide ──
      'guide_appbar_title': 'निर्देश',
      'guide_header_title': 'WhatsApp Status कैसे Save करें?',
      'guide_header_subtitle':
          'नीचे दिए गए स्टेप्स फॉलो करें और आसानी से Status Save करें।',
      'guide_title': 'स्टेप-बाय-स्टेप गाइड',
      'guide_quick_access': 'जल्दी खोलें',
      'guide_open_whatsapp': 'WhatsApp खोलें',
      'guide_tip': 'टिप: Status देखने के बाद यहाँ वापस आएं और Save करें।',
      'guide_whatsapp_not_installed': 'WhatsApp इंस्टॉल नहीं है!',
      'guide_step1_title': 'WhatsApp खोलें',
      'guide_step1_subtitle': 'नीचे दिए बटन से या खुद WhatsApp खोलें।',
      'guide_step2_title': 'Status Tab पर जाएं',
      'guide_step2_subtitle': 'WhatsApp में नीचे "Status" टैब पर टैप करें।',
      'guide_step3_title': 'Status देखें',
      'guide_step3_subtitle': 'जो Status Save करना है, उसे पूरा देख लें।',
      'guide_step4_title': 'वापस आएं',
      'guide_step4_subtitle': 'Status देखने के बाद इस App में वापस आएं।',
      'guide_step5_title': 'Select करें & Save करें',
      'guide_step5_subtitle': 'लिस्ट से Status चुनें और Save बटन दबाएं।',
    },
  };

  static String t(String languageCode, String key) {
    return _values[languageCode]?[key] ?? _values['en']![key] ?? key;
  }
}
